aw_facebook_auth:
    pattern:  /awfacebookauthbundle/auth
    defaults: { _controller: AWFacebookAuthBundle:Default:auth }

aw_facebook_auth_deauthorized:
    pattern:  /awfacebookauthbundle/deauth
    defaults: { _controller: AWFacebookAuthBundle:Default:deauth }
