<?php

namespace AW\Bundle\FacebookAuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function countAuthenticated()
    {
        return $this->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.isAuthorized = true')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function countAll()
    {
        return $this->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
